### ISSUE TITLE
set container hostname to sitename

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/shell-command#10]
While switching between multiple terminals, it gets difficult to identify which site's shell are we working on since the shell looks something like `www-data@59300522b1ce:~/htdocs$`.

If we can set hostname via ee to reflect sitename, it would look something like - `www-data@example.com:~/htdocs$`

**Comment by mrrobot47** [comment]
Closing as it has already been taken care of in https://github.com/EasyEngine/dockerfiles/pull/17
